# Mosquitto — IoT Secure Station
# MQTT (TCP) pour l'ESP32 + WebSocket pour clients web/Node-RED

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Authentification obligatoire (pas d'anonyme)
allow_anonymous false
password_file /mosquitto/config/passwd

# MQTT natif
listener 1883
protocol mqtt

# WebSocket (dashboards / clients navigateur)
listener 9001
protocol websockets
